-- MySQL Script generated by MySQL Workbench
-- Mon Jul  4 09:21:48 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`login` (
  `id_login` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `email_login` VARCHAR(45) NOT NULL COMMENT '',
  `password_login` VARCHAR(30) NOT NULL COMMENT '',
  PRIMARY KEY (`id_login`)  COMMENT '',
  UNIQUE INDEX `email_login_UNIQUE` (`email_login` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `firstname_user` VARCHAR(45) NOT NULL COMMENT '',
  `lastname_user` VARCHAR(45) NOT NULL COMMENT '',
  `companyname_user` VARCHAR(45) NULL COMMENT '',
  `adress_user` VARCHAR(45) NOT NULL COMMENT '',
  `adress2_user` VARCHAR(45) NULL COMMENT '',
  `zipcode_user` VARCHAR(45) NOT NULL COMMENT '',
  `city_user` VARCHAR(45) NOT NULL COMMENT '',
  `country_user` VARCHAR(45) NOT NULL COMMENT '',
  `phone_user` VARCHAR(45) NOT NULL COMMENT '',
  `email_user` VARCHAR(45) NOT NULL COMMENT '',
  `login_id_login` INT NOT NULL COMMENT '',
  `isadmin_user` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 : non admin\n1 : admin',
  `isactif_user` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 : non actif\n1 : actif',
  PRIMARY KEY (`id_user`, `login_id_login`)  COMMENT '',
  INDEX `fk_user_login1_idx` (`login_id_login` ASC)  COMMENT '',
  CONSTRAINT `fk_user_login1`
    FOREIGN KEY (`login_id_login`)
    REFERENCES `mydb`.`login` (`id_login`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`categorie`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`categorie` (
  `id_categorie` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name_categorie` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_categorie`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`item` (
  `id_item` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name_item` VARCHAR(45) NOT NULL COMMENT '',
  `desc_item` VARCHAR(200) NOT NULL COMMENT '',
  `image_item` BLOB NOT NULL COMMENT '',
  `quantity_item` INT NOT NULL COMMENT '',
  `prix_item` FLOAT NOT NULL COMMENT '',
  `categorie_id_categorie` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_item`)  COMMENT '',
  INDEX `fk_item_categorie1_idx` (`categorie_id_categorie` ASC)  COMMENT '',
  CONSTRAINT `fk_item_categorie1`
    FOREIGN KEY (`categorie_id_categorie`)
    REFERENCES `mydb`.`categorie` (`id_categorie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`statut`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`statut` (
  `id_statut` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name_statut` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_statut`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user_order_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user_order_item` (
  `id_order` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `user_id_user` INT NOT NULL COMMENT '',
  `item_id_item` INT NOT NULL COMMENT '',
  `date_order` DATETIME NOT NULL COMMENT '',
  `quantity_order` INT NOT NULL COMMENT '',
  `statut_id_statut` INT NOT NULL COMMENT '',
  INDEX `fk_user_has_item_item1_idx` (`item_id_item` ASC)  COMMENT '',
  INDEX `fk_user_has_item_user1_idx` (`user_id_user` ASC)  COMMENT '',
  PRIMARY KEY (`id_order`, `statut_id_statut`)  COMMENT '',
  INDEX `fk_user_order_item_statut1_idx` (`statut_id_statut` ASC)  COMMENT '',
  CONSTRAINT `fk_user_has_item_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_item_item1`
    FOREIGN KEY (`item_id_item`)
    REFERENCES `mydb`.`item` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_order_item_statut1`
    FOREIGN KEY (`statut_id_statut`)
    REFERENCES `mydb`.`statut` (`id_statut`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`promo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`promo` (
  `id_promo` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `datedebut_promo` DATETIME NOT NULL COMMENT '',
  `datefin_promo` DATETIME NOT NULL COMMENT '',
  `image_promo` BLOB NOT NULL COMMENT '',
  `item_id_item` INT NOT NULL COMMENT '',
  `montant_promo` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_promo`)  COMMENT '',
  INDEX `fk_promo_item1_idx` (`item_id_item` ASC)  COMMENT '',
  CONSTRAINT `fk_promo_item1`
    FOREIGN KEY (`item_id_item`)
    REFERENCES `mydb`.`item` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`newsletter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`newsletter` (
  `id_newsletter` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title_newsletter` VARCHAR(45) NOT NULL COMMENT '',
  `content_newsletter` VARCHAR(4000) NOT NULL COMMENT '',
  `image_newsletter` BLOB NOT NULL COMMENT '',
  `target_newsletter` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '0 : particuliers\n1 : professionnels',
  PRIMARY KEY (`id_newsletter`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`news` (
  `id_news` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `title_news` VARCHAR(45) NOT NULL COMMENT '',
  `content_news` VARCHAR(2000) NOT NULL COMMENT '',
  `image_news` BLOB NULL COMMENT '',
  `item_id_item` INT NULL COMMENT '',
  PRIMARY KEY (`id_news`)  COMMENT '',
  INDEX `fk_news_item1_idx` (`item_id_item` ASC)  COMMENT '',
  CONSTRAINT `fk_news_item1`
    FOREIGN KEY (`item_id_item`)
    REFERENCES `mydb`.`item` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departments` (
  `id_departments` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name_departments` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`id_departments`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departments_has_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departments_has_user` (
  `departments_id_departments` INT NOT NULL COMMENT '',
  `user_id_user` INT NOT NULL COMMENT '',
  PRIMARY KEY (`departments_id_departments`, `user_id_user`)  COMMENT '',
  INDEX `fk_departments_has_user_user1_idx` (`user_id_user` ASC)  COMMENT '',
  INDEX `fk_departments_has_user_departments1_idx` (`departments_id_departments` ASC)  COMMENT '',
  CONSTRAINT `fk_departments_has_user_departments1`
    FOREIGN KEY (`departments_id_departments`)
    REFERENCES `mydb`.`departments` (`id_departments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departments_has_user_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mydb`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`newsletter_has_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`newsletter_has_item` (
  `item_id_item` INT NOT NULL COMMENT '',
  `newsletter_id_newsletter` INT NOT NULL COMMENT '',
  PRIMARY KEY (`item_id_item`, `newsletter_id_newsletter`)  COMMENT '',
  INDEX `fk_item_has_newsletter_newsletter1_idx` (`newsletter_id_newsletter` ASC)  COMMENT '',
  INDEX `fk_item_has_newsletter_item1_idx` (`item_id_item` ASC)  COMMENT '',
  CONSTRAINT `fk_item_has_newsletter_item1`
    FOREIGN KEY (`item_id_item`)
    REFERENCES `mydb`.`item` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_item_has_newsletter_newsletter1`
    FOREIGN KEY (`newsletter_id_newsletter`)
    REFERENCES `mydb`.`newsletter` (`id_newsletter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tva` (
  `id_tva` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `amount_tva` FLOAT NOT NULL COMMENT '',
  `country_tva` VARCHAR(50) NOT NULL COMMENT '',
  PRIMARY KEY (`id_tva`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`departments_has_newsletter`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`departments_has_newsletter` (
  `departments_id_departments` INT NOT NULL COMMENT '',
  `newsletter_id_newsletter` INT NOT NULL COMMENT '',
  PRIMARY KEY (`departments_id_departments`, `newsletter_id_newsletter`)  COMMENT '',
  INDEX `fk_departments_has_newsletter_newsletter1_idx` (`newsletter_id_newsletter` ASC)  COMMENT '',
  INDEX `fk_departments_has_newsletter_departments1_idx` (`departments_id_departments` ASC)  COMMENT '',
  CONSTRAINT `fk_departments_has_newsletter_departments1`
    FOREIGN KEY (`departments_id_departments`)
    REFERENCES `mydb`.`departments` (`id_departments`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_departments_has_newsletter_newsletter1`
    FOREIGN KEY (`newsletter_id_newsletter`)
    REFERENCES `mydb`.`newsletter` (`id_newsletter`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
