ino_user:
    resource: "@InoUserBundle/Controller/"
    type:     annotation
    prefix:   /user

ino_shop:
    resource: "@InoShopBundle/Controller/"
    type:     annotation
    prefix:   /

ino_admin:
    resource: "@InoAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"